[package]
name = "passtoken"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.26", features = ["derive"] }
hostname = "0.4.0"
serde = { version = "1.0.217", features = ["derive"] }
